### ISSUE TITLE
Do not report unfinished spans

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin-js#365]
Currently unfinished spans are being reported and that generates weird traces where one has:

```
[
    {
        "traceId":"abc123",
        "spanId":"abc123",
        "kind":"CLIENT"
        ...
    },
    {
        "traceId":"abc123",
        "spanId":"abc123",
        "kind":"SERVER"
        ...
    }
]
```

Reason for this is that when it is a server span, the kind server is being set based on annotations (because zipkin-js is v1). I believe it will cause no harm if we report only finished spans, letting unfinished spans to be reported with the right information.

Ping @adriancole @ghermeto

**Comment by adriancole** [comment]
v1 annotations are unambiguos wrt client or server, though, right? "cs" "cr" "sr" "ss". maybe there's something else besides not being finished which is causing the confusion?

**Comment by jcchavezs** [comment]
The fact that the first chunk of span is set as client comes from https://github.com/openzipkin/zipkin-js/blame/master/packages/zipkin/src/batch-recorder.js#L153, I am still clueless on why both chunks are not being merged into a single one.

**Comment by jcchavezs** [comment]
So the concrete error is the following:

When the span takes less than the batch-recorder timeout, it is being reported in two steps (e.g. span takes 3 seconds and batch-recorder's timeout takes 1 sec, thus there are two flushes). When that happens, the payload is:

```
[
    {
        "traceId": "c3fd363580936714",
        "parentId": "f8b39211823e1ad0",
        "id": "ca88f3017211f44e",
        "kind": "SERVER",
        "name": "get /api",
        "timestamp": 1561494569981000,
        "duration": 1633449,
        "localEndpoint": {
            "serviceName": "backend",
            "ipv4": "192.168.1.35"
        },
        "tags": {
            "http.path": "/api",
            "http.status_code": "200"
        },
        "shared": true
    },
    {
        "traceId": "c3fd363580936714",
        "parentId": "f8b39211823e1ad0",
        "id": "ca88f3017211f44e",
        "kind": "CLIENT",
        "name": "get",
        "timestamp": 1561494569948000,
        "duration": 1666915,
        "localEndpoint": {
            "serviceName": "frontend"
        },
        "tags": {
            "http.path": "/api",
            "http.status_code": "200"
        }
    },
    {
        "traceId": "c3fd363580936714",
        "parentId": "c3fd363580936714",
        "id": "f8b39211823e1ad0",
        "name": "pay-me",
        "timestamp": 1561494569944000,
        "duration": 1671042,
        "localEndpoint": {
            "serviceName": "frontend"
        }
    },
    {
        "traceId": "c3fd363580936714",
        "id": "c3fd363580936714",
        "kind": "SERVER",
        "name": "get /",
        "timestamp": 1561494569941000,
        "duration": 1674931,
        "localEndpoint": {
            "serviceName": "frontend",
            "ipv4": "192.168.1.35"
        },
        "tags": {
            "http.path": "/",
            "http.status_code": "200"
        }
    },
    {
        "traceId": "c3fd363580936714",
        "id": "c3fd363580936714",
        "kind": "CLIENT",
        "name": "get",
        "localEndpoint": {
            "serviceName": "browser"
        },
        "tags": {
            "http.path": "/"
        }
    },
    {
        "traceId": "c3fd363580936714",
        "id": "c3fd363580936714",
        "kind": "CLIENT",
        "timestamp": 1561494571622000,
        "duration": 1,
        "tags": {
            "http.status_code": "200"
        }
    }
]
```
and the ui displays:

<img width="449" alt="image" src="https://user-images.githubusercontent.com/3075074/60131308-5b5b2080-9799-11e9-8140-d3176bb7ee64.png">

when the span is short (less than batch recorder timeout), the trace being reported is:

```[
    {
        "traceId": "c3fd363580936714",
        "id": "c3fd363580936714",
        "kind": "CLIENT",
        "name": "get",
        "timestamp": 1561494545230000,
        "duration": 642000,
        "localEndpoint": {
            "serviceName": "browser"
        },
        "tags": {
            "http.path": "/",
            "http.status_code": "200"
        }
    },
    {
        "traceId": "c3fd363580936714",
        "parentId": "f8b39211823e1ad0",
        "id": "ca88f3017211f44e",
        "kind": "SERVER",
        "name": "get /api",
        "timestamp": 1561494545838000,
        "duration": 12977,
        "localEndpoint": {
            "serviceName": "backend",
            "ipv4": "192.168.1.35"
        },
        "tags": {
            "http.path": "/api",
            "http.status_code": "200"
        },
        "shared": true
    },
    {
        "traceId": "c3fd363580936714",
        "parentId": "f8b39211823e1ad0",
        "id": "ca88f3017211f44e",
        "kind": "CLIENT",
        "name": "get",
        "timestamp": 1561494545819000,
        "duration": 32780,
        "localEndpoint": {
            "serviceName": "frontend"
        },
        "tags": {
            "http.path": "/api",
            "http.status_code": "200"
        }
    },
    {
        "traceId": "c3fd363580936714",
        "parentId": "c3fd363580936714",
        "id": "f8b39211823e1ad0",
        "name": "pay-me",
        "timestamp": 1561494545818000,
        "duration": 34728,
        "localEndpoint": {
            "serviceName": "frontend"
        }
    },
    {
        "traceId": "c3fd363580936714",
        "id": "c3fd363580936714",
        "kind": "SERVER",
        "name": "get /",
        "timestamp": 1561494545816000,
        "duration": 36914,
        "localEndpoint": {
            "serviceName": "frontend",
            "ipv4": "192.168.1.35"
        },
        "tags": {
            "http.path": "/",
            "http.status_code": "200"
        }
    }
]
```

and the UI displays:

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/3075074/60131395-96f5ea80-9799-11e9-9ec8-eeb1a07fb5e5.png">

Notice the first chunk has 6 items where as the second has only 5. Also. In the first chunk, there is an item like:
```
{
        "traceId": "c3fd363580936714",
        "id": "c3fd363580936714",
        "kind": "CLIENT",
        "name": "get",
        "localEndpoint": {
            "serviceName": "browser"
        },
        "tags": {
            "http.path": "/"
        }
    }
```

Which does not even have timestamp.

So, after some hours debugging and not finding any way out. I believe that since server is not merging these documents with same span ID, I still believe we should have rules in terms of what to report. Zipkin go and zipkin PHP (based on brave) do not report unfinished spans, so do we want to do that in zipkin JS? In the other hand, maybe if we debug more we could find the root cause but at this point I believe it is easier to avoid the issue by not reporting unfinished or incomplete spans (e.g. spans with no timestamp). Since this is V1, the kind is being inferred from annotations so I would not spend more time trying to find the root cause but just try to keep consistency with other libraries and when we move this to v2 model everything will be easier and less magic.

WDYT @adriancole

**Comment by adriancole** [comment]
there is a concept of finish span checking. in general it really looks like
what you are describing could be done as a unit test. is there any reason
why this has had to be done in more ad hoc way?

**Comment by adriancole** [comment]
because the code has tests about the recorder and if that is flawed we
would still need a unit test to make sure it stays fixed. if on the other
hand you are unable to create a unit test if at least could make the
zipkin-js-example fail in a branch that would be good.

it is really important to fixing this that we fix the right thing as the
batch recorder already has logic to look if a span is finished.

**Comment by jcchavezs** [comment]
I think this issue can be closed as the root problem was actually addressed in https://github.com/openzipkin/zipkin-js/pull/383

**Comment by javigomez** [comment]
Hi @jcchavezs and @adriancole , 

Seems that we are still facing this issue. 

These are our versions being used:
```
"zipkin": "^0.19.1",
    "zipkin-context-cls": "^0.19.0",
    "zipkin-instrumentation-fetch": "^0.19.1",
    "zipkin-instrumentation-hapi": "^0.19.1",
    "zipkin-transport-http": "^0.19.1"
```

This is what we see in our Zipkin:

We have 1 service called "CreateWebBFF" that on isolation reports a trace with 9 spans:
![2020-01-17-155454_1777x928_scrot-2](https://user-images.githubusercontent.com/1375475/72621725-1a4b7900-3942-11ea-8a87-32976ffd8827.png)


However, if we run 3 times like:

```
ab -c3 -n3 -H "Authorization: Bearer TOKEN"  http://127.0.0.1:9999/.../initial-payload
```

 we see this:
![2020-01-17-153956_1791x626_scrot](https://user-images.githubusercontent.com/1375475/72621615-e2dccc80-3941-11ea-8de4-e9f2356a19b4.png)

Note that it seems that some of the spans are becoming attached to different trace than the right one. In the previous image, it seems that the 2nd trace(15 spans) stole spans from the 1st (6 spans) and the 3rd (6 spans).

If we run it 5 times we see similar situation:
![2020-01-17-160244_1775x777_scrot](https://user-images.githubusercontent.com/1375475/72622140-ec1a6900-3942-11ea-8681-0f4230490e90.png)

We would like to help to debug this issue in deep. Please teach us ways to better debug it so we can come here with more helpful insights.

Thanks

**Comment by adriancole** [comment]
@javigomez I think you should use gitter as we don't use issues for open ended questions. One thing I would ask you there is if the data you have is related to reporting of unfinished spans, as it seems also explainable by a leaked context https://gitter.im/openzipkin/zipkin
